### ISSUE TITLE
revisar

### ISSUE THREAD

**Issue by reroes** [concpetosfundamentalesprogramacionaa19/practica220419-daniel-alejandro-t#1]
https://github.com/concpetosfundamentalesprogramacionaa19/practica220419-daniel-alejandro-t/blob/13b28376fcb7cd70b25edbc36957842733cfa299/demo2.py#L15

salidaSuma = int(dato1)+int(dato2)

cambiar por 

salidaSuma = int(dato1) + int(dato2)

**Comment by daniel-alejandro-t** [comment]
Listo
